name: Deploy to Droplet
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: root  
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 33342
        script: |
          cd /root/devopsuser/bot-app/discord-botty-doe25
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt --upgrade
          systemctl restart discord-bot 